const express=require("express"),http=require("http"),path=require("path"),bcrypt=require("bcryptjs"),jwt=require("jsonwebtoken");
const {Server}=require("socket.io");const {Pool}=require("pg");
const app=express(),server=http.createServer(app),io=new Server(server,{cors:{origin:"*"}});
const PORT=Number(process.env.PORT||10000),SECRET=process.env.JWT_SECRET||"change-me",ROOT=path.join(__dirname,"..");
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:{rejectUnauthorized:false},max:10}):null;
app.use(express.json({limit:"2mb"}));const db=(q,p=[])=>{if(!pool)throw Error("DATABASE_URL missing");return pool.query(q,p)};
async function init(){if(!pool)return;await db(`CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,username VARCHAR(32) UNIQUE NOT NULL,name VARCHAR(100) NOT NULL,password_hash TEXT NOT NULL,avatar TEXT,bio TEXT DEFAULT '',online BOOLEAN DEFAULT FALSE,last_seen TIMESTAMPTZ DEFAULT NOW(),created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS chats(id BIGSERIAL PRIMARY KEY,type VARCHAR(16) NOT NULL DEFAULT 'private',title VARCHAR(150) NOT NULL,owner_id BIGINT REFERENCES users(id),created_at TIMESTAMPTZ DEFAULT NOW());
CREATE TABLE IF NOT EXISTS chat_members(chat_id BIGINT REFERENCES chats(id) ON DELETE CASCADE,user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,role VARCHAR(20) DEFAULT 'member',joined_at TIMESTAMPTZ DEFAULT NOW(),PRIMARY KEY(chat_id,user_id));
CREATE TABLE IF NOT EXISTS messages(id BIGSERIAL PRIMARY KEY,chat_id BIGINT REFERENCES chats(id) ON DELETE CASCADE,user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,text TEXT NOT NULL,reply_to BIGINT REFERENCES messages(id),edited BOOLEAN DEFAULT FALSE,created_at TIMESTAMPTZ DEFAULT NOW(),updated_at TIMESTAMPTZ DEFAULT NOW());
CREATE INDEX IF NOT EXISTS messages_chat_id_id ON messages(chat_id,id);`)}
const makeToken=u=>jwt.sign({id:String(u.id),username:u.username},SECRET,{expiresIn:"30d"});
function auth(req,res,next){try{let h=req.headers.authorization||"";req.user=jwt.verify(h.replace(/^Bearer /,""),SECRET);next()}catch{res.status(401).json({error:"Unauthorized"})}}
app.get("/api/health",async(req,res)=>{let database=false;try{if(pool){await db("SELECT 1");database=true}}catch{}res.json({ok:true,server:"online",database,socketio:true})});
app.post("/api/auth/register",async(req,res)=>{try{let u=String(req.body.username||"").trim().toLowerCase().replace(/^@/,""),n=String(req.body.name||"").trim(),p=String(req.body.password||"");if(!/^[a-z0-9_]{3,32}$/.test(u)||n.length<2||p.length<6)return res.status(400).json({error:"Invalid registration data"});let r=await db("INSERT INTO users(username,name,password_hash) VALUES($1,$2,$3) RETURNING id,username,name,avatar,bio,online,last_seen",[u,n,await bcrypt.hash(p,12)]);res.json({ok:true,token:makeToken(r.rows[0]),user:r.rows[0]})}catch(e){res.status(e.code==="23505"?409:500).json({error:e.code==="23505"?"Username already exists":"Registration failed"})}});
app.post("/api/auth/login",async(req,res)=>{try{let u=String(req.body.username||"").trim().toLowerCase().replace(/^@/,""),r=await db("SELECT * FROM users WHERE username=$1",[u]);if(!r.rows[0]||!(await bcrypt.compare(String(req.body.password||""),r.rows[0].password_hash)))return res.status(401).json({error:"Invalid login"});let x=r.rows[0];await db("UPDATE users SET online=TRUE,last_seen=NOW() WHERE id=$1",[x.id]);delete x.password_hash;res.json({ok:true,token:makeToken(x),user:x})}catch(e){res.status(500).json({error:"Login failed"})}});
app.get("/api/me",auth,async(req,res)=>{let r=await db("SELECT id,username,name,avatar,bio,online,last_seen FROM users WHERE id=$1",[req.user.id]);res.json({ok:true,user:r.rows[0]})});
app.get("/api/users/search",auth,async(req,res)=>{let q=String(req.query.q||"").trim();if(!q)return res.json({ok:true,users:[]});let r=await db("SELECT id,username,name,avatar,bio,online,last_seen FROM users WHERE username ILIKE $1 OR name ILIKE $1 ORDER BY online DESC,name LIMIT 30",[`%${q}%`]);res.json({ok:true,users:r.rows})});
app.get("/api/chats",auth,async(req,res)=>{let r=await db(`SELECT c.id,c.type,c.title,c.created_at,(SELECT text FROM messages m WHERE m.chat_id=c.id ORDER BY m.id DESC LIMIT 1) last_message FROM chats c JOIN chat_members cm ON cm.chat_id=c.id WHERE cm.user_id=$1 ORDER BY c.created_at DESC`,[req.user.id]);res.json({ok:true,chats:r.rows})});
app.post("/api/chats/private",auth,async(req,res)=>{let u=String(req.body.username||"").trim().toLowerCase().replace(/^@/,""),x=await db("SELECT id,username,name FROM users WHERE username=$1",[u]);if(!x.rows[0])return res.status(404).json({error:"User not found"});let old=await db(`SELECT c.id FROM chats c JOIN chat_members a ON a.chat_id=c.id AND a.user_id=$1 JOIN chat_members b ON b.chat_id=c.id AND b.user_id=$2 WHERE c.type='private' LIMIT 1`,[req.user.id,x.rows[0].id]);if(old.rows[0])return res.json({ok:true,chat:old.rows[0]});let c=await db("INSERT INTO chats(type,title,owner_id) VALUES('private',$1,$2) RETURNING id,type,title",[x.rows[0].name,req.user.id]);await db("INSERT INTO chat_members(chat_id,user_id) VALUES($1,$2),($1,$3)",[c.rows[0].id,req.user.id,x.rows[0].id]);res.json({ok:true,chat:c.rows[0]})});
app.get("/api/chats/:id/messages",auth,async(req,res)=>{let id=Number(req.params.id),m=await db("SELECT 1 FROM chat_members WHERE chat_id=$1 AND user_id=$2",[id,req.user.id]);if(!m.rows[0])return res.status(403).json({error:"Not a member"});let r=await db(`SELECT m.id,m.chat_id,m.user_id,m.text,m.reply_to,m.edited,m.created_at,u.username,u.name,u.avatar FROM messages m JOIN users u ON u.id=m.user_id WHERE m.chat_id=$1 ORDER BY m.id DESC LIMIT 100`,[id]);res.json({ok:true,messages:r.rows.reverse()})});
app.post("/api/chats/:id/messages",auth,async(req,res)=>{let id=Number(req.params.id),t=String(req.body.text||"").trim();if(!t)return res.status(400).json({error:"Empty message"});let m=await db("SELECT 1 FROM chat_members WHERE chat_id=$1 AND user_id=$2",[id,req.user.id]);if(!m.rows[0])return res.status(403).json({error:"Not a member"});let r=await db("INSERT INTO messages(chat_id,user_id,text,reply_to) VALUES($1,$2,$3,$4) RETURNING *",[id,req.user.id,t,req.body.reply_to||null]),u=await db("SELECT username,name,avatar FROM users WHERE id=$1",[req.user.id]),msg={...r.rows[0],...u.rows[0]};io.to("chat:"+id).emit("message:new",msg);res.json({ok:true,message:msg})});
app.patch("/api/messages/:id",auth,async(req,res)=>{let t=String(req.body.text||"").trim(),r=await db("UPDATE messages SET text=$1,edited=TRUE,updated_at=NOW() WHERE id=$2 AND user_id=$3 RETURNING *",[t,req.params.id,req.user.id]);if(!r.rows[0])return res.status(404).json({error:"Message not found"});io.to("chat:"+r.rows[0].chat_id).emit("message:edited",r.rows[0]);res.json({ok:true,message:r.rows[0]})});
app.delete("/api/messages/:id",auth,async(req,res)=>{let r=await db("DELETE FROM messages WHERE id=$1 AND user_id=$2 RETURNING id,chat_id",[req.params.id,req.user.id]);if(!r.rows[0])return res.status(404).json({error:"Message not found"});io.to("chat:"+r.rows[0].chat_id).emit("message:deleted",r.rows[0]);res.json({ok:true})});
io.use((s,n)=>{try{s.user=jwt.verify(s.handshake.auth?.token||"",SECRET);n()}catch{n(new Error("Unauthorized"))}});
io.on("connection",s=>{db("UPDATE users SET online=TRUE,last_seen=NOW() WHERE id=$1",[s.user.id]).catch(()=>{});s.on("chat:join",id=>db("SELECT 1 FROM chat_members WHERE chat_id=$1 AND user_id=$2",[id,s.user.id]).then(r=>{if(r.rows[0])s.join("chat:"+id)}).catch(()=>{}));s.on("typing",d=>{if(d?.chatId)s.to("chat:"+d.chatId).emit("typing",{userId:s.user.id})});s.on("disconnect",()=>db("UPDATE users SET online=FALSE,last_seen=NOW() WHERE id=$1",[s.user.id]).catch(()=>{}))});
app.use(express.static(path.join(ROOT,"client")));app.get("/{*splat}",(req,res)=>res.sendFile(path.join(ROOT,"client","index.html")));
init().then(()=>server.listen(PORT,"0.0.0.0",()=>console.log("Telegram Zero on "+PORT))).catch(e=>{console.error(e);process.exit(1)})